AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: 'Stack cfstack-eedb015-2025-grupo-a com os recursos do grupo A da Especializacao Engenharia de Dados e Big Data turma de 2024 para a aula de Projeto Integrador'

Parameters:

  DataUrl:
    Type: String

  TaxiZoneLookUpUrl:
    Type: String

  TaxiZoneShapeFileUrl:
    Type: String

  BucketArtifacts:
    Type: String

Resources:

############################################################################################################
########################################      BUCKETS      #################################################
############################################################################################################

  BucketRaw:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-raw"
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

  BucketTrusted:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-trusted"
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

  BucketAnalytics:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-analytics"
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

############################################################################################################
########################################       ROLES       #################################################
############################################################################################################

  IAMRoleFunctionIngestion:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-function-ingestion-role"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub "${BucketRaw.Arn}*"
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

  IAMRoleGlueJobTrusted:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-read-raw"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${BucketRaw.Arn}*"
                  - !Sub "arn:aws:s3:::${BucketArtifacts}*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:PutObject
                Resource: !Sub "${BucketTrusted.Arn}*"
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetPartition
                  - glue:GetPartitions
                  - glue:GetCatalogImportStatus
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/tlc_trip
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/trusted_tlc_trip
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/default
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/tlc_trip/taxi_zone_lookup
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:GetPartitions
                  - glue:CreateTable
                  - glue:UpdateTable
                  - glue:CreatePartition
                  - glue:BatchCreatePartition
                  - glue:UpdatePartition
                  - glue:BatchUpdatePartition
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/trusted_tlc_trip
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/trusted_tlc_trip/yellow_tripdata
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

  IAMRoleGlueJobDelivery:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-read-trusted"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${BucketTrusted.Arn}*"
                  - !Sub "arn:aws:s3:::${BucketArtifacts}*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:PutObject
                Resource: !Sub "${BucketAnalytics.Arn}*"
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetPartition
                  - glue:GetPartitions
                  - glue:GetCatalogImportStatus
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/delivery_tlc_trip
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/trusted_tlc_trip
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/default      
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/trusted_tlc_trip/yellow_tripdata
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:GetPartitions
                  - glue:CreateTable
                  - glue:UpdateTable
                  - glue:CreatePartition
                  - glue:BatchCreatePartition
                  - glue:UpdatePartition
                  - glue:BatchUpdatePartition
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/delivery_tlc_trip
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/delivery_tlc_trip/*
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

############################################################################################################
########################################      LAMBDAS      #################################################
############################################################################################################

  FunctionTripDataIngestion:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-ingestion-trip-data-function'
      Handler: 'lambda-trip-data-ingestion.handler'
      Architectures:
        - 'arm64'
      MemorySize: 2048
      Timeout: 900
      Runtime: 'python3.12'
      Layers:
        - !Ref WebScrappingLayer
      Role: !GetAtt IAMRoleFunctionIngestion.Arn
      CodeUri: './lambdas'
      Environment:
        Variables:
          NYC_TLC_URL: !Ref DataUrl
          BUCKET_NAME: !Ref BucketRaw
          BUCKET_PREFIX: 'tlc_trip'
      Tags:
        "Projeto": 'Projeto Integrador'

  FunctionGeoDataIngestion:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-ingestion-geo-data-function'
      Handler: 'lambda-geo-data-ingestion.handler'
      Architectures:
        - 'arm64'
      MemorySize: 2048
      Timeout: 900
      Runtime: 'python3.12'
      Layers:
        - !Ref WebScrappingLayer
      Role: !GetAtt IAMRoleFunctionIngestion.Arn
      CodeUri: './lambdas'
      Environment:
        Variables:
          TAXI_ZONE_LOOKUP_URL: !Ref TaxiZoneLookUpUrl
          TAXI_ZONE_SHAPEFILE_URL: !Ref TaxiZoneShapeFileUrl
          BUCKET_NAME: !Ref BucketRaw
          BUCKET_PREFIX: 'tlc_trip'
          SHAPEFILE_PREFIX: 'shapefiles'
      Tags:
        "Projeto": 'Projeto Integrador'

############################################################################################################
########################################      LAYERS       #################################################
############################################################################################################

  WebScrappingLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${AWS::StackName}-web-scrapping-layer'
      Description: 'A layer which contains web scrapping libraries'
      ContentUri: './layers/web-scrapping-layer/web-scrapping-layer.zip'
      CompatibleArchitectures:
        - 'arm64'
      CompatibleRuntimes:
        - 'python3.12'

############################################################################################################
########################################     Glue Jobs    ##################################################
############################################################################################################

  GlueJobTrustedLayer:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${AWS::StackName}-trusted-glue-job'
      Role: !GetAtt IAMRoleGlueJobTrusted.Arn
      Command:
        Name: 'glueetl'
        ScriptLocation: !Sub 's3://${BucketArtifacts}/glues_scripts/glue_job_trusted.py'
        PythonVersion: '3'
      DefaultArguments:
        "--enable-glue-datacatalog": ""
        "--enable-metrics": ""
        "--sourcebucket": !Ref BucketRaw
        "--sourceprefix": 'tlc_trip/yellow_tripdata'
        "--sourcedatabase": !Ref GlueDatabase
        "--sourcezonetable": 'taxi_zone_lookup'
        "--targetbucket": !Ref BucketTrusted
        "--targetdatabase": !Ref GlueDatabaseTrusted
        "--targettable": 'yellow_tripdata'
        "--month": ""
      MaxRetries: 0
      GlueVersion: '5.0'
      Timeout: 60
      NumberOfWorkers: 2
      WorkerType: 'G.1X'

  GlueJobDeliveryLayer:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${AWS::StackName}-delivery-glue-job'
      Role: !GetAtt IAMRoleGlueJobDelivery.Arn
      Command:
        Name: 'glueetl'
        ScriptLocation: !Sub 's3://${BucketArtifacts}/glues_scripts/glue_job_delivery.py'
        PythonVersion: '3'
      DefaultArguments:
        "--enable-glue-datacatalog": ""
        "--enable-metrics": ""                
        "--sourcedatabase": !Ref GlueDatabaseTrusted
        "--targetbucket": !Ref BucketAnalytics
        "--targetdatabase": !Ref GlueDatabaseAnalytics
        "--targettable": 'yellow_tripdata'
        "--month": ""
        "--tables": "summarized_trip_cost,trip_peak_time,trip_peak_zones"
      MaxRetries: 0
      GlueVersion: '5.0'
      Timeout: 60
      NumberOfWorkers: 2
      WorkerType: 'G.1X'


############################################################################################################
########################################   Glue Catalog    #################################################
############################################################################################################

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: tlc_trip
        Description: "Database para armazenar tabelas da camada Raw do TLC Trip"

  GlueDatabaseTrusted:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: trusted_tlc_trip
        Description: "Database para armazenar tabelas da camada Trusted do TLC Trip"

  GlueDatabaseAnalytics:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: analytics_tlc_trip
        Description: "Database para armazenar tabelas da camada Analytics do TLC Trip"

  GlueTable:
    Type: AWS::Glue::Table
    DependsOn: GlueDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: tlc_trip
      TableInput:
        Name: yellow_tripdata
        Description: "Tabela de viagens do Yellow Taxi armazenada no S3"
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: "parquet"
          parquet.compression: "SNAPPY"
        StorageDescriptor:
          Columns:
            - Name: VendorID
              Type: int
            - Name: tpep_pickup_datetime
              Type: timestamp
            - Name: tpep_dropoff_datetime
              Type: timestamp
            - Name: passenger_count
              Type: double
            - Name: trip_distance
              Type: double
            - Name: rate_code_id
              Type: int
            - Name: store_and_fwd_flag
              Type: string
            - Name: pu_location_id
              Type: int
            - Name: do_location_id
              Type: int
            - Name: payment_type
              Type: int
            - Name: fare_amount
              Type: double
            - Name: extra
              Type: double
            - Name: mta_tax
              Type: double
            - Name: tip_amount
              Type: double
            - Name: tolls_amount
              Type: double
            - Name: improvement_surcharge
              Type: double
            - Name: total_amount
              Type: double
            - Name: congestion_surcharge
              Type: double
          Location: !Sub s3://${AWS::StackName}-raw/tlc_trip/yellow_tripdata/
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe

############################################################################################################
########################################   Glue Catalog    #################################################
############################################################################################################

  DataQualityCompletenessRuleset:
    Type: AWS::Glue::DataQualityRuleset
    Properties:
      Name: !Sub '${AWS::StackName}-trusted-completeness-ruleset'
      Description: 'Data Quality Ruleset for trusted_tlc_trip.yellow_tripdata table'
      Ruleset: 'Rules = [
        IsComplete "vendorid",
        IsComplete "pickup_datetime",
        IsComplete "dropoff_datetime",
        IsComplete "passenger_count",
        IsComplete "trip_distance",
        IsComplete "rate_code_id",
        IsComplete "pickup_neighborhood",
        IsComplete "pickup_zone",
        IsComplete "pickup_service_zone",
        IsComplete "dropoff_neighborhood",
        IsComplete "dropoff_zone",
        IsComplete "dropoff_service_zone",
        IsComplete "payment_type",
        IsComplete "fare_amount",
        IsComplete "extra",
        IsComplete "mta_tax",
        IsComplete "tip_amount",
        IsComplete "tolls_amount",
        IsComplete "total_amount",
        IsComplete "partition_dt" ]'
      TargetTable:
        DatabaseName: !Ref GlueDatabaseTrusted
        TableName: 'yellow_tripdata'

  DataQualityAnomaliesRuleset:
    Type: AWS::Glue::DataQualityRuleset
    Properties:
      Name: !Sub '${AWS::StackName}-trusted-anomalies-ruleset'
      Description: 'Data Quality Ruleset for trusted_tlc_trip.yellow_tripdata table'
      Ruleset: 'Rules = [
        ColumnValues "passenger_count" > 0 where "passenger_count IS NOT NULL",
        ColumnValues "total_amount" > 0 where "total_amount IS NOT NULL",
        ColumnValues "vendorid" in [1, 2, 6, 7],
        ColumnValues "rate_code_id" in [1, 2, 3, 4, 5, 6, 99],
        ColumnValues "payment_type" in [0, 1, 2, 3, 4, 5, 6] ]'
      TargetTable:
        DatabaseName: !Ref GlueDatabaseTrusted
        TableName: 'yellow_tripdata'
