AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: 'Stack eedb015-2024-g2 com os recursos do grupo 2 da Especialização Engenharia de Dados e Big Data turma de 2024 para a aula de Projeto Integrador'

Parameters:

  Course:
    Default: eedb
    Type: String

  Subject:
    Default: 015-2024
    Type: String

  Group:
    Default: grupo-a
    Type: String

Resources:

############################################################################################################
########################################      BUCKETS      #################################################
############################################################################################################

  BucketArtifacts:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Course}${Subject}-${Group}-${AWS::AccountId}-artifacts
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

  BucketIngestion:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Course}${Subject}-${Group}-${AWS::AccountId}-ingestion
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

  BucketRaw:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Course}${Subject}-${Group}-${AWS::AccountId}-raw
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Projeto
          Value: Projeto Integrador
