AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: 'Stack eedb015-2024-g2 com os recursos do grupo 2 da Especialização Engenharia de Dados e Big Data turma de 2024 para a aula de Projeto Integrador'

Parameters:

  Course:
    Default: eedb
    Type: String

  Subject:
    Default: 015-2024
    Type: String

  Group:
    Default: grupo-a
    Type: String

Resources:

############################################################################################################
########################################      BUCKETS      #################################################
############################################################################################################

  BucketArtifacts:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Course}${Subject}-${Group}-${AWS::AccountId}-artifacts
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

  BucketIngestion:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Course}${Subject}-${Group}-${AWS::AccountId}-ingestion
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

  BucketRaw:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Course}${Subject}-${Group}-${AWS::AccountId}-raw
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
                - states.amazonaws.com
                - events.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-Role"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
      Tags:
        - Key: Projeto
          Value: Projeto Integrador

  FunctionIngestion:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ingestion-function"
      Handler: 'lambda-producer.lambda_handler'
      Runtime: 'python3.9'
      Role: !GetAtt IAMRole.Arn
      CodeUri:
        Bucket: !Ref BucketArtifacts
        Key: 'lambda-scripts/lambda-ingestion.zip'
      Timeout: 900
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref BucketIngestion
            Events: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: 'data/'
      Tags:
        "Projeto": "Projeto Integrador"